import type { State } from "./types";

export const SEED_VERSION = 4;

const d = (days: number) => new Date(Date.now() + days * 86400000).toISOString();
const at = (days: number, hour: number, min = 0) => {
  const t = new Date(Date.now() + days * 86400000);
  t.setHours(hour, min, 0, 0);
  return t.toISOString();
};

export function seedState(): State {
  return {
    _v: SEED_VERSION,
    view: "today",
    dayKey: new Date().toDateString(),
    seededAt: new Date().toISOString(),
    lastDropAt: at(0, 6, 0),
    lastTopic: "risk",
    leads: [
      {
        id: "l1",
        company: "Harbor & Vine Restaurant",
        contact: "Dario Ruiz",
        email: "dario@harborvine.com",
        source: "referral",
        value: 18500,
        stage: "followup",
        notes: "Site survey done Feb. Waiting on owner sign-off; sensitive about upfront cost.",
        createdAt: d(-21),
        lastTouchAt: d(-8),
        touches: 3,
        cold: true,
      },
      {
        id: "l2",
        company: "Bluebird Dental",
        contact: "Dr. Emily Chan",
        email: "emily@bluebirddental.com",
        source: "google-ads",
        value: 9200,
        stage: "contacted",
        notes: "Replied to first email. Wants a number before a call.",
        createdAt: d(-9),
        lastTouchAt: d(-2),
        touches: 1,
      },
      {
        id: "l3",
        company: "Kite Fitness Club",
        contact: "Marcus Webb",
        email: "marcus@kitefitness.co",
        source: "website",
        value: 24000,
        stage: "new",
        notes: "Inbound form yesterday: two locations, tired of peak-rate bills.",
        createdAt: d(-1),
        lastTouchAt: d(-1),
        touches: 0,
      },
      {
        id: "l4",
        company: "Maple Row Realty",
        contact: "Janet Okafor",
        email: "janet@maplerow.com",
        source: "referral",
        value: 31000,
        stage: "won",
        notes: "Signed yesterday after positive Gmail reply. Install scheduled.",
        createdAt: d(-34),
        lastTouchAt: d(-1),
        touches: 6,
        wonAt: d(-1),
        reply: { sentiment: "positive", at: d(-1) },
      },
      {
        id: "l5",
        company: "Cedar & Sage Spa",
        contact: "Lena Ortiz",
        email: "lena@cedarsage.spa",
        source: "linkedin",
        value: 7800,
        stage: "followup",
        notes: "Liked the case study, asked to revisit after their renovation.",
        createdAt: d(-16),
        lastTouchAt: d(-7),
        touches: 2,
        cold: true,
      },
      {
        id: "l6",
        company: "Ironclad CrossFit",
        contact: "Sam Pierce",
        email: "sam@ironcladcf.com",
        source: "manual",
        value: 12000,
        stage: "lost",
        notes: "Went with a cheaper installer. Keep for re-engagement next year.",
        createdAt: d(-40),
        lastTouchAt: d(-12),
        touches: 4,
      },
      {
        id: "l7",
        company: "Northwind Roastery",
        contact: "Tomas Berg",
        email: "tomas@northwindroast.com",
        source: "trade-show",
        value: 15400,
        stage: "contacted",
        notes: "Met at GreenBuild expo. Roasting machines run all day — strong fit.",
        createdAt: d(-6),
        lastTouchAt: d(-3),
        touches: 1,
      },
      {
        id: "l8",
        company: "Willow Creek Veterinary",
        contact: "Dr. Priya Nair",
        email: "priya@willowcreekvet.com",
        source: "website",
        value: 11500,
        stage: "new",
        notes: "Inbound form: new building, wants solar before summer load hits.",
        createdAt: d(-2),
        lastTouchAt: d(-2),
        touches: 0,
      },
    ],
    drafts: [
      {
        id: "dr1",
        leadId: "l1",
        kind: "nudge",
        subject: "Closing the loop — Harbor & Vine solar",
        body: "Hi Dario,\n\nI'll keep this short. It's been about a week since my last note, and I don't want this to sit in your inbox forever.\n\nTwo things that may help: the survey we did in February still holds, and a financing split would put your first payment after the system starts cutting your bill.\n\nWorth a 15-minute call Thursday? If the timing is wrong, just say so and I'll close the file.\n\n— Alex",
        createdAt: at(0, 8, 15),
        status: "ready",
        why: "Lead went cold: 8 days since last touch (your threshold is 6). Used your “warm, plain-spoken” tone, referenced the February site survey from the lead notes, and kept it to 74 words — your samples average 80. Ends with an easy out, which your best-converting nudges all include.",
      },
      {
        id: "dr2",
        leadId: "l3",
        kind: "outreach",
        subject: "Two locations, one energy bill question",
        body: "Hi Marcus,\n\nYou mentioned in your form that peak-rate bills are eating into margins at both clubs. That's exactly the load profile solar flattens best.\n\nWe did this for Maple Row Realty last month — 38% off their commercial bill in the first full cycle. I can sketch the same math for Kite in about 20 minutes, using your actual usage data.\n\nTuesday or Wednesday better for a quick call?\n\n— Alex",
        createdAt: at(0, 8, 16),
        status: "ready",
        why: "Fresh inbound lead (yesterday, website form). Matched your opener style — question first, no jargon — and pulled in their own words (“peak-rate bills”, “two locations”) from the form notes. Credibility anchor: the Maple Row win Sales closed yesterday.",
      },
    ],
    ideas: [
      {
        id: "id1",
        title: "Stalled-Pipeline Rescue Nurture",
        objective: "Re-engage leads stuck 6+ days in follow-up before they die",
        audience: "2 stalled leads (Harbor & Vine, Cedar & Sage) + future cold leads",
        channel: "Email + WhatsApp broadcast",
        message: "“Still worth it?” — one short proof story (Maple Row, −38% bill) + one easy ask",
        format: "2-message sequence, 3 days apart",
        budgetMin: 0,
        budgetMax: 120,
        why: "Sales data shows 2 leads are past your 6-day cold threshold right now, and your own history says follow-ups sent within 3 days convert ~2× better. Cost is under your $500/week cap — and as always I propose the budget, you approve the spend.",
        createdAt: at(0, 6, 0),
        status: "new",
      },
      {
        id: "id2",
        title: "Google Ads Creative Refresh — Commercial Solar",
        objective: "Stop the CTR bleed on your live search campaign",
        audience: "Commercial property owners searching “commercial solar” in your metro",
        channel: "Google Ads",
        message: "Swap generic panels imagery for real install photos + the 38% number in the headline",
        format: "2 new responsive search ads + 1 display variant",
        budgetMin: 150,
        budgetMax: 300,
        why: "“Google Ads — Commercial Solar” has run 3 weeks and its CTR slipped to 1.1% — below your 1.5% floor. Classic creative fatigue. Marketing can see Sales is converting trade-show leads better right now, so real-photo creative should close the gap.",
        createdAt: at(0, 6, 0),
        status: "new",
      },
      {
        id: "id3",
        title: "Before/After Install Reel — Maple Row",
        objective: "Turn yesterday's closed deal into social proof while it's fresh",
        audience: "Local business owners on Instagram; retarget site visitors",
        channel: "Instagram Reels",
        message: "30-sec timelapse: empty roof → live array → first bill screenshot (with permission)",
        format: "1 reel + 3 story cuts",
        budgetMin: 60,
        budgetMax: 180,
        why: "Maple Row closed yesterday via the Spring Referral Push — your notes say visual proof posts get ~3× more saves than static ads, and Operations confirms the install photo set is already in the Vault.",
        createdAt: at(0, 6, 0),
        status: "new",
      },
      {
        id: "id4",
        title: "Referral Loop Email — Past Customers",
        objective: "Systematize the referral channel that produced 2 of your last 3 wins",
        audience: "All installed customers, 6+ months in",
        channel: "Email",
        message: "“Know a roof like yours?” — $250 credit for a signed referral",
        format: "Single send + automated follow-up",
        budgetMin: 0,
        budgetMax: 90,
        why: "Approved yesterday. Attribution in the shared store shows referral-sourced leads closed at the highest value ($31k Maple Row). You asked me to make it repeatable.",
        createdAt: d(-1),
        status: "approved",
      },
    ],
    campaigns: [
      {
        id: "c1",
        name: "Spring Referral Push",
        channel: "Email + referral",
        status: "live",
        budget: 400,
        spent: 260,
        ctr: 4.6,
        leadsGenerated: 5,
        closedFromCampaign: 1,
        startedAt: d(-14),
      },
      {
        id: "c2",
        name: "Google Ads — Commercial Solar",
        channel: "Google Ads",
        status: "live",
        budget: 900,
        spent: 705,
        ctr: 1.1,
        leadsGenerated: 6,
        closedFromCampaign: 0,
        startedAt: d(-21),
        flagged: "CTR 1.1% is below your 1.5% floor — see today's idea drop for a creative refresh.",
      },
      {
        id: "c3",
        name: "Instagram Awareness — Install Stories",
        channel: "Instagram",
        status: "paused",
        budget: 300,
        spent: 140,
        ctr: 2.2,
        leadsGenerated: 3,
        closedFromCampaign: 0,
        startedAt: d(-30),
      },
    ],
    calendar: [
      { id: "cal1", date: d(0), label: "Send referral loop email", channel: "Email" },
      { id: "cal2", date: d(1), label: "Shoot Maple Row install reel", channel: "Instagram" },
      { id: "cal3", date: d(2), label: "New Google Ads creatives live", channel: "Google Ads" },
      { id: "cal4", date: d(4), label: "WhatsApp nurture — message 1", channel: "WhatsApp" },
      { id: "cal5", date: d(6), label: "Case study: Harbor & Vine (if won)", channel: "Email" },
    ],
    tasks: [
      {
        id: "t1",
        title: "Order inverters for Maple Row install",
        owner: "Alex",
        due: d(1),
        status: "open",
        linkedLeadId: "l4",
        createdAt: d(-1),
      },
      {
        id: "t2",
        title: "Submit Bluebird Dental permit application",
        owner: "Field crew",
        due: d(3),
        status: "open",
        createdAt: d(-4),
      },
      {
        id: "t3",
        title: "Quarterly safety audit — ladders & harnesses",
        owner: "Alex",
        due: d(6),
        status: "open",
        createdAt: d(-10),
      },
      {
        id: "t4",
        title: "Site survey — Harbor & Vine",
        owner: "Field crew",
        due: d(-9),
        status: "done",
        createdAt: d(-15),
      },
      {
        id: "t5",
        title: "Onboard Maple Row — schedule install week",
        owner: "Alex",
        due: d(7),
        status: "open",
        linkedLeadId: "l4",
        createdAt: d(-1),
      },
    ],
    vendors: [
      {
        id: "v1",
        name: "VoltEdge Supply",
        category: "Inverters & racking",
        status: "delayed",
        note: "Shipment slipped 5 days — affects Maple Row install.",
        lastCheckedAt: d(-1),
      },
      {
        id: "v2",
        name: "SunPanel Co",
        category: "Panels",
        status: "ok",
        note: "Current pricing locked through Q3.",
        lastCheckedAt: d(-3),
      },
      {
        id: "v3",
        name: "City Permit Office",
        category: "Permits",
        status: "watch",
        note: "Backlog rumors — applications taking 6–8 days instead of 4.",
        lastCheckedAt: d(-2),
      },
    ],
    risks: [
      {
        id: "r1",
        key: "vendor-v1",
        title: "Maple Row install at risk — inverter shipment delayed",
        why: "Sales closed Maple Row ($31k) yesterday and the install task is due in 1 day, but VoltEdge Supply just reported a 5-day slip. That's a 4-day dependency gap on your first deliverable for a brand-new customer — highest-risk moment in the relationship.",
        severity: "high",
        recommendation: "1) Call VoltEdge for a partial shipment. 2) SunPanel Co shows in-stock inverters (status OK) — price a swap. 3) If slip > 2 days, tell Maple Row now with a revised date; I can draft that note for your approval.",
        status: "open",
        category: "Supply chain",
        escalated: true,
        createdAt: at(0, 6, 2),
      },
      {
        id: "r2",
        key: "task-t2",
        title: "Bluebird permit due in 3 days while permit office slows",
        why: "Your permit task is due in 3 days and the City Permit Office is on watch status (6–8 day backlog vs. normal 4). Submitting on the due date will almost certainly push Bluebird's install past the date Dr. Chan was quoted.",
        severity: "medium",
        recommendation: "Submit the application tomorrow morning, not on the due date. If backlog confirms, reset expectations with Bluebird this week.",
        status: "open",
        category: "Deadlines",
        createdAt: at(0, 6, 2),
      },
    ],
    docs: [
      {
        id: "doc1",
        name: "Vendor Agreement — VoltEdge Supply.pdf",
        type: "contract",
        tags: ["contract", "vendor", "volledge", "renewal"],
        person: "VoltEdge Supply",
        content: "Master supply agreement between Meridian Solar and VoltEdge Supply LLC. Term: 12 months, auto-renews with 30-day notice. Pricing schedule B for inverters and racking. Renewal window opens March 15.",
        summary: "12-month master supply agreement, auto-renewal clause, pricing schedule B.",
        uploadedAt: d(-95),
        size: 482000,
        expiresAt: d(40),
        versions: [{ v: 1, at: d(-95), name: "Vendor Agreement — VoltEdge Supply.pdf", note: "Signed original" }],
      },
      {
        id: "doc2",
        name: "Electrical Contractor License — Class A.pdf",
        type: "license",
        tags: ["license", "compliance", "renewal"],
        content: "Class A electrical contractor license, state board registration. Valid through this quarter. Renewal requires 16 continuing-education credits on file.",
        summary: "Class A license — renewal needs 16 CE credits on file.",
        uploadedAt: d(-200),
        size: 210000,
        expiresAt: d(12),
        versions: [{ v: 1, at: d(-200), name: "Electrical Contractor License — Class A.pdf", note: "Current term" }],
      },
      {
        id: "doc3",
        name: "Invoice #2041 — Maple Row deposit.pdf",
        type: "invoice",
        tags: ["invoice", "maple-row", "deposit"],
        person: "Maple Row Realty",
        content: "Invoice 2041. 50% deposit for 86kW commercial installation, Maple Row Realty. Paid. Balance due on commissioning.",
        summary: "50% deposit invoice for the 86kW Maple Row install. Paid.",
        uploadedAt: d(-1),
        size: 96000,
        versions: [{ v: 1, at: d(-1), name: "Invoice #2041 — Maple Row deposit.pdf", note: "Issued at signing" }],
      },
      {
        id: "doc4",
        name: "Installation Agreement — Maple Row Realty.pdf",
        type: "contract",
        tags: ["contract", "maple-row", "signed"],
        person: "Maple Row Realty",
        content: "Installation agreement for 86kW rooftop array. Scope, warranty 25 years, payment schedule, interconnection responsibilities.",
        summary: "Signed installation agreement for the 86kW array.",
        uploadedAt: d(-1),
        size: 512000,
        autoFiled: "Auto-filed when Sales marked Maple Row won — the orchestrator passed the closed-deal event to the Vault.",
        versions: [{ v: 1, at: d(-1), name: "Installation Agreement — Maple Row Realty.pdf", note: "Countersigned" }],
      },
      {
        id: "doc5",
        name: "NDA — Cedar & Sage Spa.docx",
        type: "contract",
        tags: ["nda", "contract", "cedar-sage"],
        person: "Cedar & Sage Spa",
        content: "Mutual non-disclosure agreement ahead of sharing energy usage data. Cedar & Sage Spa. Two-year term.",
        summary: "Mutual NDA signed before they share utility data.",
        uploadedAt: d(-9),
        size: 44000,
        versions: [
          { v: 1, at: d(-9), name: "NDA — Cedar & Sage Spa.docx", note: "Draft sent" },
          { v: 2, at: d(-2), name: "NDA — Cedar & Sage Spa (countersigned).docx", note: "Countersigned copy" },
        ],
      },
      {
        id: "doc6",
        name: "Site Survey — Harbor & Vine.pdf",
        type: "process",
        tags: ["survey", "harbor-vine", "sales"],
        person: "Harbor & Vine Restaurant",
        content: "Rooftop site survey: 4,200 sq ft unshaded, 200A service, panel layout for 62kW proposed system. Photos attached.",
        summary: "Survey for a proposed 62kW system; 200A service confirmed.",
        uploadedAt: d(-14),
        size: 1840000,
        versions: [{ v: 1, at: d(-14), name: "Site Survey — Harbor & Vine.pdf", note: "Field crew upload" }],
      },
      {
        id: "doc7",
        name: "Brand Guidelines 2026.pdf",
        type: "brand",
        tags: ["brand", "guidelines", "marketing"],
        content: "Meridian Solar brand voice: practical, neighborly, no jargon. Logo lockups, color hex values, photography style, do/don't examples.",
        summary: "Voice, logo lockups, colors, photo style — what Marketing checks every morning.",
        uploadedAt: d(-60),
        size: 3200000,
        versions: [{ v: 1, at: d(-60), name: "Brand Guidelines 2026.pdf", note: "Current" }],
      },
    ],
    activity: [
      {
        id: "a1",
        at: at(0, 8, 16),
        agent: "sales",
        text: "Drafted first outreach to Kite Fitness Club (new inbound).",
        why: "Fresh website lead; matched your tone sample and used their own form words.",
      },
      {
        id: "a2",
        at: at(0, 8, 15),
        agent: "sales",
        text: "Drafted a cold-nudge for Harbor & Vine (8 days, past your 6-day threshold).",
        why: "Cold-lead rule triggered; nudge style mirrors your best-converting template.",
      },
      {
        id: "a3",
        at: at(0, 6, 5),
        agent: "vault",
        text: "Flagged “Electrical Contractor License — Class A” — expires in 12 days.",
        why: "Expiry scan runs nightly; renewal needs 16 CE credits per the document text.",
      },
      {
        id: "a4",
        at: at(0, 6, 2),
        agent: "ops",
        text: "Escalated high-severity risk: Maple Row install at risk (VoltEdge 5-day slip).",
        why: "Dependency gap of 4 days on a task due tomorrow — too urgent for the daily summary.",
      },
      {
        id: "a5",
        at: at(0, 6, 0),
        agent: "marketing",
        text: "6:00 AM idea drop generated 3 ideas.",
        why: "Scheduled trigger. Drew on 2 stalled Sales leads, an underperforming Google Ads campaign, and yesterday's Maple Row win.",
      },
      {
        id: "a6",
        at: at(0, 6, 0),
        agent: "orchestrator",
        text: "Bundled the morning digest: 3 ideas, 2 drafts, 1 escalated risk, 1 expiring doc.",
      },
      {
        id: "a7",
        at: d(-1),
        agent: "orchestrator",
        text: "Routed “deal closed” event from Sales → Operations and Document Vault.",
      },
      {
        id: "a8",
        at: d(-1),
        agent: "ops",
        text: "Auto-created “Onboard Maple Row — schedule install week” after Sales closed the deal.",
        why: "Your auto-ops-on-win rule: every closed deal gets an onboarding task within 24h.",
      },
      {
        id: "a9",
        at: d(-1),
        agent: "vault",
        text: "Auto-filed “Installation Agreement — Maple Row Realty” (tags: contract, signed).",
        why: "Closed-deal event included the countersigned PDF; auto-tagged from document text.",
      },
      {
        id: "a10",
        at: d(-1),
        agent: "sales",
        text: "Lead Maple Row Realty marked Won ($31,000) — positive reply tracked from Gmail.",
        why: "Reply-tracking saw Janet's “let's do it” response; you confirmed the close.",
      },
      {
        id: "a11",
        at: d(-2),
        agent: "marketing",
        text: "Idea “Referral Loop Email” approved → added to content calendar for today.",
      },
      {
        id: "a12",
        at: d(-3),
        agent: "ops",
        text: "Vendor VoltEdge Supply marked delayed (your manual input) — watching downstream tasks.",
      },
    ],
    notices: [
      {
        id: "n1",
        at: at(0, 6, 5),
        agent: "orchestrator",
        title: "Morning brief is ready",
        body: "Overnight: 3 new marketing ideas, 2 sales drafts waiting for your approval, 1 escalated operations risk (Maple Row install), and 1 document expiring in 12 days.",
        kind: "digest",
        read: false,
        actionView: "today",
        actionLabel: "Open brief",
      },
      {
        id: "n2",
        at: at(0, 6, 2),
        agent: "ops",
        title: "Escalated: Maple Row install at risk",
        body: "VoltEdge shipment slipped 5 days; your install task is due in 1 day. High severity — not waiting for the daily summary.",
        kind: "alert",
        read: false,
        actionView: "ops",
        actionLabel: "See risk",
      },
      {
        id: "n3",
        at: at(0, 8, 17),
        agent: "sales",
        title: "2 drafts ready — nothing sends without you",
        body: "A cold-nudge for Harbor & Vine and first outreach to Kite Fitness are reviewed and queued in your Gmail draft flow.",
        kind: "sales",
        read: false,
        actionView: "sales",
        actionLabel: "Review drafts",
      },
      {
        id: "n4",
        at: at(0, 6, 5),
        agent: "vault",
        title: "License expires in 12 days",
        body: "Electrical Contractor License — Class A needs renewal (16 CE credits required per the document).",
        kind: "doc",
        read: false,
        actionView: "vault",
        actionLabel: "View document",
      },
      {
        id: "n5",
        at: at(0, 6, 0),
        agent: "marketing",
        title: "6:00 AM idea drop — 3 new ideas",
        body: "A stalled-pipeline nurture, a Google Ads creative refresh, and a Maple Row before/after reel.",
        kind: "idea",
        read: false,
        actionView: "marketing",
        actionLabel: "Review ideas",
      },
      {
        id: "n6",
        at: d(-1),
        agent: "orchestrator",
        title: "Cross-agent handoff complete — Maple Row win",
        body: "Sales closed → Ops created onboarding tasks → Vault filed the signed agreement → Marketing credited the Spring Referral Push.",
        kind: "digest",
        read: true,
      },
    ],
    settings: {
      ownerName: "Alex",
      businessName: "Meridian Solar",
      gmailConnected: true,
      gmailAccount: "alex@meridiansolar.com",
      coldDays: 6,
      cadenceDays: 3,
      toneName: "Warm, plain-spoken, no fluff",
      toneSample:
        "Hi {first name},\n\nShort one: we put 86kW on Maple Row's roof last month and their first bill dropped 38%. Happy to run the same math on your numbers — takes 20 minutes and you keep the sheet either way.\n\nWorth a quick call this week?\n\n— Alex",
      brandVoice:
        "Practical, neighborly, zero jargon. We're the crew that shows up on time. Numbers over adjectives.",
      weeklyBudgetCap: 500,
      vaultAccess: ["Alex (Owner)"],
      autoOpsOnWin: true,
    },
    chat: [
      {
        id: "m1",
        from: "agent",
        agent: "orchestrator",
        text: "Morning, Alex. Overnight I routed 3 marketing ideas, 2 sales drafts, and 1 escalated ops risk into your inbox.\n\nAsk me anything in plain language. Try:\n• “Why is the Maple Row install at risk?”\n• “Pull up the VoltEdge agreement”\n• “Draft a follow-up for Bluebird”\n• “Run an ops health check”",
        at: at(0, 6, 6),
      },
    ],
    chatOpen: false,
    typing: null,
    toasts: [],
  };
}
